server:
  port : 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true